### ISSUE TITLE
Tracking text from json like android

### ISSUE THREAD

**Issue by jatinfl15** [airbnb/lottie-ios#1281]
## Check these before submitting:
- [ ] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [x] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Animation JSON

is it possible to track text from json & change it manually like android?
